### PR TITLE
Clear code; Fix ArrayLists; Optimize code

### PR DESCRIPTION
**Pull request by LordRibblesdale**
+ Delete all Object extension (implicit for all objects)
+ Fix some ArrayList<> types when possible (some of them didn't have a specific type, this could be a problem when wrongly filled with other objects)
++ This optimized a lot of casts (because of generic type, all objects of these insterested arrays had to be casted every time)
+ Clear some if conditions (like if(<condition> == true) -> if (<condition>)) 
+ Clear some returns (some of them will return directly boolean method instead of using a if else)
+ Fix some double divisions (I thought some could have returned integer instead of double)
+ Clear some deprecated calls (like new Integer(), new Double(), new Boolean())
++ In cases of Integer, Boolean and Double, some returns are automated by Java, so it isn't necessary to call methods like booleanValue()
+ Clear some code (like in Basis.saveToStream(..) method, where code was duplicated with only a little change during writeUTF(..) calls)
+ Use for each instead of for in cases of multiple calls of an array element
+ Change some conditions (item.indexOf("1D_") > -1 ->item.contains("1D_"))
+ Change some methods, adviced by IDE (like: Boolean.valueOf(..) -> Boolean.parseBoolean(..))

### CODE REVIEW

**Comment by marko-radosavljevic** [comment]
I... I already started reviewing first PR :cry: 

Its fine tho, just don't forget to check it ^^

**Comment by LordRibblesdale** [comment]
I'm sorry >.< I got a bit sad when I tried to undo commits but didn't make it. 
I thank you for your help in the other PR

**Comment by marko-radosavljevic** [comment]
It's fine, I can leave one PR open for you after merging, so you can play with git if you want :)
this is fun and very good _game_ to play if you want to practice git skills: [link](https://learngitbranching.js.org/)! :tada:

**Comment by marko-radosavljevic** [comment]
There is a surprise waiting for you in the first PR! :open_mouth:

**Review by marko-radosavljevic — APPROVED** [review]
Thanks! ^^

Just fix this one thing CodeQL is reporting ^^

**Comment by marko-radosavljevic** [comment]
Ah, fix this one thing CodeQL is reporting ^^

**Pull request merged**
