### PR TITLE
Setup autostyle gradle plugin.

### PR DESCRIPTION
**Pull request by weisJ**
* Setup autostyle gradle plugin.
* Add github workflow to automatically check style violations.

This PR adds the configuration for the autostyle gradle plugin.
Files can be automatically formatted using
````
gradlew autostyleApply
````
and checked using
````
gradlew autostyleCheck
````
It also adds a new github workflow which checks for style violations on each commit.

This PR is still a draft as there still needs to be made a decisions about what formatting options are used.
Two options would be
- Using the eclipse formatting option with a custom `style.eclipseconfig.xml` file.
- Using [google java format](https://github.com/google/google-java-format). Maybe with the [`aosp`](https://source.android.com/setup/contribute/code-style#order-import-statements) flag enabled as it uses 4 instead of 2 spaces (and the project currently uses 4 spaces).

I would included the first formatting run with this PR and as already mentioned in #24 would incorporate the line normalization and file encoding conversion in this process.

### CODE REVIEW

**Comment by marko-radosavljevic** [comment]
Looks good, I will merge after #19 is done. And yeah, include first formatting run with it! ^^

I vote for google style with 4 spaces, would like others to chime in too.

**Comment by weisJ** [comment]
I just looked a bit further into the aosp style and it looks like it forces you to have a maximum line length of `100` (the whole google java formatted does so). I myself are much more a fan of a `120` character limit myself.
There is an official eclipse-config for the google style though, so we could use that with some custom adjustments.

**Comment by marko-radosavljevic** [comment]
I agree on the 120, I mostly voted for google style because I know it's popular, and I assumed most devs would be comfortable with it.

I would still appreciate others chiming in, if not, do 4 spaces and 120 char width google style.

**Comment by marko-radosavljevic** [comment]
Don't forget to fix _CodeQL_ workflow.

**Pull request merged**
