### PR TITLE
[Old] Umbrella PR - Convert icons to SVG (Replaced by #64)

### LINKED ISSUE #27: Convert icons to svg
Currently icons are either `16x16` or `24x24`. For high resolution screens this isn’t an appropriate resolution anymore. Replacing the current icons with svg version solves this issue and will allow us to move further with updating the look and feel (more context as soon as I get the the laf integrated).

All currently used icons are located at [resources/Bilder](https://github.com/MyLibreLab/MyLibreLab/tree/master/src/main/resources/Bilder). Some images are available multiple times with different resolutions. They will only be replaced once of course.

Also some of those icons need to be renamed to have a more descriptive name. For some I don’t even know what they depict or used for so that needs to be investigated beforehand.

Generally I think we should aim for a more modern/flat design for the icons, similar to those of IntelliJ.
Note: The IntelliJ icons are available as svg versions to download and are compatible with our license, so we should be fine to use them. A list of all icons can be found [here](https://jetbrains.design/intellij/resources/icons_list/)
___
This could be marked as good first issue.

### PR DESCRIPTION
**Pull request by weisJ**
This is an umbrella pull request to keep track of the work on #27.
If you want to contribute some icons please open a pull request into this branch.

All currently used icons are located at [resources/Bilder](https://github.com/weisj/MyLibreLab/tree/svg_icons/src/main/resources/Bilder).
New icons should be placed in [resources/com/github/mylibrelab/ui/icons/](https://github.com/weisj/MyLibreLab/tree/svg_icons/src/main/resources/com/github/mylibrelab/ui/icons).

- If you contribute a new icon please don't delete the old icon file.

- If possible please use an icon already available in IntelliJ. The icons are available at https://jetbrains.design/intellij/resources/icons_list/

- Some icons are listed with multiple resolutions. Those only need to be replaced once.

- [x] Logo
- [ ] about16
- [ ] about24
- [ ] add_package
- [ ] ajax-loader
- [ ] application_osx_terminal
- [ ] applications-internet
- [ ] arrow_black_left
- [ ] arrow_black_right
- [ ] arrow_refresh
- [ ] back16
- [ ] blast16
- [ ] blast24
- [ ] bold16
- [ ] bold24
- [ ] - [ ] box_front_open
- [ ] cascadeWindows16
- [ ] cascadeWindows24
- [ ] Check
- [ ] Check
- [ ] close16
- [ ] close24
- [ ] closeAllWindows16
- [ ] closeAllWindows24
- [ ] color16
- [ ] color24
- [ ] compile
- [ ] compile16
- [ ] copy16
- [ ] copy24
- [ ] Cross
- [ ] Cross
- [ ] Cross9x9
- [ ] Cross9x9
- [ ] cut16
- [ ] cut24
- [ ] de
- [ ] delete16
- [ ] delete24
- [ ] document-new
- [ ] document-new_VM
- [ ] document-open
- [ ] document_properties
- [ ] edit-redo
- [ ] edit-undo
- [ ] ElementImage
- [ ] emptyIcon16
- [ ] emptyIcon24
- [ ] es
- [ ] exit16
- [ ] exit24
- [ ] export16
- [ ] export24
- [ ] fastForward16
- [ ] fastForward24
- [ ] file_save_as
- [ ] find16
- [ ] find24
- [ ] font16
- [ ] font24
- [ ] forward16
- [ ] gplv3-88x31
- [ ] graphBoolean
- [ ] graphBoolean16x16
- [ ] graphDouble
- [ ] graphDouble16x16
- [ ] hammer16
- [ ] hammer24
- [ ] help16
- [ ] help24
- [ ] home16
- [ ] icon_2
- [ ] icon_16
- [ ] icon_32
- [ ] icon_64
- [ ] import16
- [ ] import24
- [ ] information
- [ ] Information16
- [ ] Information24
- [ ] isProject
- [ ] italic16
- [ ] italic24
- [ ] Kopie von Check
- [ ] legend
- [ ] Legende
- [ ] lgplv3-88x31
- [ ] lightning16
- [ ] lightning24
- [ ] logoUcatolica
- [ ] logoUcatolica
- [ ] mask16
- [ ] mask24
- [ ] myopenlab_logo_2016
- [ ] myopenlab_logo_Oficial
- [ ] netBeans
- [ ] new16
- [ ] new24
- [ ] notAProject
- [ ] open16
- [ ] open24
- [ ] open24Project
- [ ] open24VM
- [ ] package
- [ ] paste16
- [ ] paste24
- [ ] pause16
- [ ] pause24
- [ ] play16
- [ ] play24
- [ ] playX24
- [ ] preferences-desktop
- [ ] preferences-desktop-locale
- [ ] print16
- [ ] print24
- [ ] properties16
- [ ] properties24
- [ ] redo
- [ ] redo16
- [ ] redo24
- [ ] Resume
- [ ] Resume16
- [ ] reverse16
- [ ] reverse24
- [ ] rewind16
- [ ] rewind24
- [ ] save
- [ ] save16
- [ ] save16
- [ ] save24
- [ ] saveAs16
- [ ] saveAsJPG16
- [ ] separator
- [ ] startX
- [ ] Step16
- [ ] Step16
- [ ] Step24
- [ ] Step24
- [ ] stop16
- [ ] stop24
- [ ] storage
- [ ] storage24x24
- [ ] testpoint
- [ ] testPointWhite
- [ ] tileHorizontal16
- [ ] tileHorizontal24
- [ ] tileVertical16
- [ ] tileVertical24
- [ ] underline16
- [ ] underline24
- [ ] undo
- [ ] undo16
- [ ] undo24
- [ ] up16
- [ ] us
- [ ] utilities-terminal
- [ ] variables
- [ ] variables16
- [ ] view-refresh
- [ ] zip16
- [ ] zoom1_124
- [ ] zoomIn16
- [ ] zoomIn24
- [ ] zoomOut16
- [ ] zoomOut24

### CODE REVIEW

**Comment by marko-radosavljevic** [comment]
Personally, I think intelliJ icons are too flat and minimal, and they will look weird in contrast to current outdated Elements design, maybe I'm wrong tho.. Depends how big they are?

**Comment by weisJ** [comment]
Ultimately the element icons will have to be adjusted too.

**Comment by alehel** [comment]
A nice organized way of changing all the icons! I'll do some work on a few of these in a couple of days :).

**Comment by weisJ** [comment]
Closing due to #64

**Pull request closed without merging**
