### PR TITLE
Replace Logging by Tinylog

### PR DESCRIPTION
**Pull request by Stephen-AI**
I replaced all the println with tinylog's static logger. This is excluding the printlns within a try-catch block to avoid merge conflicts. Since the goal is to avoid merge conflicts I also did not replace the Java Logger previously in use if it was within the try-catch block also

### CODE REVIEW

**Comment by marko-radosavljevic** [comment]
Seems like git doesn't like the way you fixed the line endings, we need to fix that. ^^

But yeah, everything outside of try and catch blocks should be either `Logger.info()` or `Logger.debug()`, and possibly `Logger.error()'. You decide in which category print belongs.

**Comment by marko-radosavljevic** [comment]
Run `./gradlew autostyleApply` and push changes

**Comment by Stephen-AI** [comment]
> Run `./gradlew autostyleApply` and push changes

Oh man I already pushed changes that converts it back to CRLF

**Comment by marko-radosavljevic** [comment]
You need to revert your changes to the _.gitattributes_, and then run `./gradlew autostyleApply`. With `git status` you should see no red files, and then push.

**Comment by Stephen-AI** [comment]
> You need to revert your changes to the _.gitattributes_, and then run `./gradlew autostyleApply`. With `git status` you should see no red files, and then push.

My fork does not have autostyleApply in the gradlew. I could copy the one from the main repo and run it.

**Comment by marko-radosavljevic** [comment]
Now run `./gradlew autostyleApply and push changes`

**Comment by marko-radosavljevic** [comment]
Now run `./gradlew autostyleApply and push changes`

Btw, you can check if you actually fixed before pushing, using: git status (uncommitted changes), git log (commit history and branches), git diff (diff between files).

**Comment by marko-radosavljevic** [comment]
I'm actually invested in this epic battle! ^^

https://learngitbranching.js.org/ this is great game you can play to learn git, it's also fun!

**Comment by Stephen-AI** [comment]
> Now run `./gradlew autostyleApply and push changes`
> 
> Btw, you can check if you actually fixed before pushing, using: git status (uncommitted changes), git log (commit history and branches), git diff (diff between files).
> 
> You need first to confirm with git status and git pull that you are up to date with master, and then when you are absolutely sure your fork is up to date, do autostyle and push.

I'm sorry. I've never done a rebase on git before so this was a little confusing for me. Hopefully this fixes the problem and we don't have to deal with line endings again

**Comment by marko-radosavljevic** [comment]
Ah, now I see where things went wrong, fetched your branch to check.
Will show you how to locate the issue and how to fix it tomorrow, leave it for now ^^

**Comment by marko-radosavljevic** [comment]
I'm too  busy now for explaining, but hop in our [discord]( discord.gg/rcvvuxt ), and I will help you with few git and github things (some things are specific to github)!

That said, I'm merging this! :tada:

**Pull request merged**
