### PR TITLE
Convert gradle script from groovy to kotlin.

### PR DESCRIPTION
**Pull request by weisJ**
- Convert gradle script from groovy to kotlin.
- Add bom to manage dependency version.
- Use consistent file encoding in build.gradle.kts and .editorconfig

Converting the gradle script to kotlin gives better ide integration and it's a lot easier to work with because of
the benefits of strong typing.

This PR also adds a bom for managing dependency versions.

The last change is to make it easier for new contributors to get started. Having the project in a windows specific file encoding
is rather undesirable. Also it's a bit weird that the current `build.gradle` and `.editorconfig` files conflict each other with the specified file encoding. 

Ideally I'd like to convert all current files to `UTF-8` encoding and let git renormalize all files to ensure the correct line endings (which also weren't quite configured in the `.editorconfig`).
Additionally as there currently is no check for the code style this is something we should think about. I already have made good experience with [autostyle](https://github.com/autostyle/autostyle). Some features we could benefit from:
- Task to automatically apply or check the code style (the check would be integrated as a github action).
- Support for eclipse style configs or google java style (the first one is more versatile but involves more planning)
- Automatically handle license headers for files.

If we decide to add autostyle, the first formatting iteration could be combined with the encoding change and normalization to only have one commit which touches more or less every file.

### CODE REVIEW

**Comment by MaSven** [comment]
A tip for the conversion to utf-8 would be to use dostounix. This tool is installed in every linux distro.

**Comment by marko-radosavljevic** [comment]
I like the changes. ^^
Especially appreciate all the comments! Great work.

Is this ready to be merged?

**Comment by weisJ** [comment]
I'm currently integrating autostyle and would like to do the one run that changes all files first. Because this will introduce a lot of merge conflicts it might be worth while to wait for #19 first.

**Comment by marko-radosavljevic** [comment]
Sure, I just feel like autostyle integration should be a separate PR, to keep the git history cleaner.
Ping me when you feel ready for a merge.

**Comment by weisJ** [comment]
In this case feel free to merge this one.

**Pull request merged**
