### PR TITLE
Update to Jdk 15.

### PR DESCRIPTION
**Pull request by weisJ**

### CODE REVIEW

**Comment by weisJ** [comment]
CodeQL currently doesn't support Java 15 https://github.com/github/codeql/issues/4281

**Comment by marko-radosavljevic** [comment]
That's a bummer, we can wait for the fix before switching to jdk15.

**Comment by marko-radosavljevic** [comment]
The issue that was blocking this PR seems to be resolved.

**Comment by weisJ** [comment]
Yes that's good news. However I did run into a problem with autostyle when using some of the newer syntax. I'm still waiting for my fix to be merged (https://github.com/autostyle/autostyle/pull/24). However I have an idea on how to solve the problem without the fix needed, which would allow us to move forward.

**Review by marko-radosavljevic — APPROVED** [review]
Love the refactorings. :+1:

**Pull request merged**
