### PR TITLE
Fix spelling mistakes in GUI property files

### PR DESCRIPTION
**Pull request by sohanian**
Fixes spelling and grammar mistakes in property files of GUI resources

### CODE REVIEW

**Comment by marko-radosavljevic** [comment]
Welcome to the project! ^^

Is this everything IDE catches? What tools did you use to find all spelling mistakes?

**Comment by sohanian** [comment]
I went through the property files. I didn't use a tool as I'm a native English speaker. These are very basic fixes. I ran the program to go through and check for things that didn't make sense. There's still a lot of mixed German and English, I'll try to help with that as well.

**Comment by marko-radosavljevic** [comment]
Ah, now I get it, this is fix for the GUI text/properties English spelling mistakes.

I think some mistypes are not covered, for example there are two "Numeriks" I currently see, one in the Window dropdown menu, one in the toolbar. There is "Physik" element, etc.

Can you try to hunt down all misspelled English in the GUI currently? Click everywhere and snipe those strings in the codebase. You can also open some examples and check elements and properties in them.

All names are also inconsistent currently. For example word delimiter is sometimes `_` or `-` or `space` and sometimes there is no delimiter at all, but we can do this in a separate PR.

And welcome to the project! ^^

**Comment by sohanian** [comment]
I'll go through and do some more when I have some time. I'm not sure when that will be, so a separate PR would be good.

**Pull request merged**
