### PR TITLE
Fix firmata element not found

### PR DESCRIPTION
**Pull request by marko-radosavljevic**
This should fix issue #6.
Tried to keep changes as minimal as possible for this hotfix.

### CODE REVIEW

**Comment by koppor** [comment]
I like the refactorings 🎉 

Is it possible to fix it even without adding a `jar` file? Refs https://github.com/MyLibreLab/MyLibreLab/issues/13

Could you try to add following to build.gradle?

```groovy
implementation 'org.bidib.jbidib.org.qbang.rxtx:rxtxcomm:2.2'
```

Think, we just forgot it - or included the wrong rxtxcom dependency in build gradle:

https://github.com/MyLibreLab/MyLibreLab/blob/d5fa168a0e10540e2cee7186db1e1308200f95a9/build.gradle#L52

**Comment by marko-radosavljevic** [comment]
Thanks, I just fixed things that blew in my face while I was working on this fix. There are still many empty catch blocks, which I intend to refactor in separate PR.

That's the thing, `jar` file was already there. There are many `jar` files left after merging /elements. I wanted to deal with this later, because we still haven't solved the issue of installing these libs. I should have been more clear about it tho, my bad.

Yeah, we need both dependencies, one is main `jar` and other is compiled binaries for all platforms. The problem i have with that `qbang.rxtx:rxtxcomm:2.2` artifact is its version. It clashes with my distro's RXTX dependency for Arduino IDE, and I assume its same for other platforms. I think we should discuss this in #13, because I have no experience with these libs.

**Comment by marko-radosavljevic** [comment]
Also to further clarify this fix, the whole issue with Firmata was because of NPE on driver load:

https://github.com/MyLibreLab/MyLibreLab/blob/d5fa168a0e10540e2cee7186db1e1308200f95a9/src/main/java/VisualLogic/Element.java#L798-L805

Here url4 is null because it fails the check, and that null value is passed to `ladeClasseDriver`.
So it's unrelated to RXTX lib. When we figure out how to deal with dependencies, we can refactor this whole part because it would be no longer needed.

**Review by MaSven — APPROVED** [review]

**Comment by marko-radosavljevic** [comment]
This was originally created as quick hotfix.

Before merging this, we need to figure out #13, how to install these dependencies and to test them on all platforms.
Already installed Win VM, so we should be able to finally deal with this soon.

**Pull request closed without merging**
