### PR TITLE
Limit element positioning to left mouse button.

### LINKED ISSUE #35: Limit elements positioning to left mouse button.
When moving elements one should only be able to do so using the left mouse button.
For example if one uses the right button to open the context menu and keeps the button pressed as soon as the
mouse leaves the menu the elements in the background makes a big jump.

### PR DESCRIPTION
**Pull request by alehel**
resolves #35

### CODE REVIEW

**Comment by alehel** [comment]
I see I needed to run ./gradlew autostyleApply. I'll fix and push once the other tests are complete.

**Comment by marko-radosavljevic** [comment]
Ah, this was so fast its almost anticlimactic. ^^

Welcome to the project! :tada:

**Comment by alehel** [comment]
Thanks @marko-radosavljevic. I'll admit I'd already spent about 30 minutes looking at the code before I asked to be assigned :p. Came here because of Hacktoberfest, but this project seems really interesting. I'll probably be sticking around :).

**Comment by weisJ** [comment]
Could you please include the `autostyle` run the changes of your first commit? Otherwise this looks good.

**Review by weisJ — CHANGES_REQUESTED** [review]
Could you please include the `autostyle` run to the changes of your first commit? Otherwise this looks good.

**Comment by alehel** [comment]
Sure. Probably won't have time tonight, but will fix tomorrow.

**Pull request closed without merging**
