### PR TITLE
Extract all useful html docs from ./elements to ./docs/html-docs

### PR DESCRIPTION
**Pull request by marko-radosavljevic**
This will extract all useful html docs from ./elements/* to ./docs, and remove old ones.

Full folder structure is kept, so we can know which doc belongs to which element. Files that are empty, or containing garbage data are pruned.

List of all commands that are used on this data:
```
 3765  grep -inr --include \*.html '1111' ./
 3766  grep -inrl --include \*.html '1111' ./ | xargs rm
 3767  grep -inrl --include \*.html 'text here' ./ | xargs rm
 3769  grep -inr --include \*.html 'text here' ./
 3772  grep -inrl --include \*.html '1111' ./ | xargs rm
 3773  grep -inr --include \*.html '1111' ./
 3774  grep -inr --include \*.html 'text here' ./
 3775  grep -inrl --include \*.html 'text here' ./ | xargs -d '\n' rm
 3778* grep -inr --include \*.html 'qwert' ./
 3779  grep -inrl --include \*.html 'qwert' ./ | xargs -d '\n' rm
 3780* grep -inr --include \*.html 'here your text' ./
 3781  grep -inrl --include \*.html 'here your text' ./ | xargs -d '\n' rm
 3782* grep -inr --include \*.html ' text' ./
 3783* grep -inr --include \*.html 'hier den' ./
 3784  grep -inrl --include \*.html 'hier den' ./ | xargs -d '\n' rm
 3792* grep -inr --include \*.html '' ./
 3801  find ./ -type f -empty -delete
 3804  find ./ \( -type d -name .git -prune \) -name "*.html" -o -type f -print0 | xargs -0 sed -i '/^\s*$/d'
 3807  find ./ \( -type d -name .git -prune \) -o -type f -name "*.html"  -print0 | xargs -0 sed -i '/^\s*$/d'
 3809  find ./ -type f -empty -delete
 3812* grep -inr --include \*.html '12345' ./
 3813  grep -inrl --include \*.html '12345' ./ | xargs -d '\n' rm
 3815* grep -inr --include \*.html 'TEST0' ./
 3816  grep -inrl --include \*.html 'TEST02' ./ | xargs -d '\n' rm
 3857* grep -inr --include \*.html -Pazo '<html>*\n*  <head>*\n*  </head>*\n*  <body>*\n*  </body>*\n*</html>' ./
 3858  grep -inrl --include \*.html -Pazo '<html>*\n*  <head>*\n*  </head>*\n*  <body>*\n*  </body>*\n*</html>' ./ | xargs -d '\n' rm
 3880* grep -inr --include \*.html 'Aqu. el texto' ./
 3900* grep -inr --include \*.html -Pazo '<html>*\n*<head>*\n*<title>Aqu(?s)' ./
 3901  grep -inrl --include \*.html -Pazo '<html>*\n*<head>*\n*<title>Aqu(?s)' ./ | xargs -d '\n' rm
 3902* grep -inr --include \*.html -Pazo '<html>*\n*  <head>*\n  *</head>*\n*  <body>*\n*    <p style="margin-top: 0">' ./
 3903  grep -inrl --include \*.html -Pazo '<html>*\n*  <head>*\n  *</head>*\n*  <body>*\n*    <p style="margin-top: 0">' ./ | xargs -d '\n' rm
 3906  find . -name '*.html' -exec cp --parents \{\} ../docs/html-docs \;
 3921* find ./docs/html-docs -type d -empty -delete  -name 'doc' 
```

### CODE REVIEW

**Comment by weisJ** [comment]
Why not move the docs to https://github.com/MyLibreLab/user-documentation instead? I see this happening sooner or later anyway.

**Comment by marko-radosavljevic** [comment]
You are right, I totally forgot about that repo. Closing this and opening PR over there.

**Comment by weisJ** [comment]
Could you open another PR with all the file deletions?

**Comment by marko-radosavljevic** [comment]
I will include those changes in my next PR that will remove all unnecessary files. Thanks for reminding me tho ^^

There is no need for me to open separate PR for every file type individually, it will be one PR with one commit for each file type/group deleted, so we can easily document all the changes and commands that are run on the data. Also, we can easily revert batch of changes, if that is needed, and test things easier (dependencies etc.)  before merging.

Big structural changes to the codebase should be also documented [here](https://github.com/MyLibreLab/MyLibreLab/blob/dev/docs/conversion-of-myopenlab-repository.md) (its currently outdated). We can also add commit refs or PR links there. Because we are making huge changes all-around, so we should document everything carefully.

Besides documenting changes for the future of this project, we should strive to make contributing easy for the current users. After each change, we should add something to our docs. We discussed adding javadocs guidelines; I'm sure after rewriting GUI you noticed some other flaws we should avoid. You can make short tutorial how to use new GUI API's, something very basic, etc

**Pull request closed without merging**
