### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jha-vineet69**
Corrected some minor spelling mistakes.

### CODE REVIEW

**Comment by marko-radosavljevic** [comment]
You don't have to close PR's, just commit new changes, they will be here automagically! ^^

**Comment by jha-vineet69** [comment]
I messed up with the branches and then ended up deleting the branch itself. Sorry for your trouble.

**Comment by marko-radosavljevic** [comment]
No worries, just wanted to help you. ^^

**Comment by marko-radosavljevic** [comment]
You can also check other docs for spelling mistakes:
https://mylibrelab.github.io/user-documentation/
https://github.com/MyLibreLab/MyLibreLab/blob/master/docs/conversion-of-myopenlab-repository.md

**Comment by jha-vineet69** [comment]
How do I make changes in user documentation?

**Comment by koppor** [comment]
The user documentation is available at https://github.com/MyLibreLab/user-documentation. As soon as a change is made in the `master` branch, it is automatically converted by the Jekyll instance (hosted by GitHub) and published at https://mylibrelab.github.io/user-documentation/.

Background of GH pages available at https://pages.github.com/.

**Pull request merged**
