### PR TITLE
Issue #5

### PR DESCRIPTION
**Pull request by LordRibblesdale**

### CODE REVIEW

**Comment by marko-radosavljevic** [comment]
Seems good, tell me when it's ready for a merge! ^^

**Comment by LordRibblesdale** [comment]
Sure ;) right now, my PCs have some problems virtualizing a Linux environment, so I'll try to fix this and see if everything is ok!

**Comment by marko-radosavljevic** [comment]
Nice testing strategy btw, push to master, and see what breaks :p

**Comment by LordRibblesdale** [comment]
No exceptions at startup and all icons are loaded on JDK 15 & Fedora 32

**Comment by marko-radosavljevic** [comment]
I know, I was just joking. Thanks for adding additional info tho! ^^

And thanks for contributing to this project, PR is merged! :heart:

**Pull request merged**
